### ISSUE TITLE
Implement better Consensus Algorithm

### ISSUE THREAD

**Issue by alexdovzhanyn** [alexdovzhanyn/odyn#19]
Currently, nodes validate that a block is legitimate based off of the following:

1. Blocks prev_hash must equal the hash of the latest block on the chain
2. Blocks index must be one higher than the latest on the chain
3. The blocks hash is validly calculated

We need to make it so that the integrity of the block depends also on the transactions within it. For starters: 
1. The coinbase of a block should pay a valid dividend to the miner. Nodes should agree on what a valid block reward is. If a miner tries to claim a block reward that is not the amount that is agreed upon, the block is invalid. What number should this be?
2. To discourage miners from mining empty blocks, the block must have at least one transaction other than the coinbase.
3. Each transaction within the block must be valid (disallowing double spends, #6 is a blocker for this)

Are there any other criteria that should be added to the consensus algorithm?

**Comment by Pavel-Durov** [comment]
@alexdovzhanyn maybe block reward should be affected by the length of the blockchain as it is set in bitcoin system.

**So we can say for example:**  
0-100,000 blocks-------------100 Odyn
100,001-200,000 blocks------50  Odyn
200,001-300,000 blocks------25  Odyn
 etc...

Seems to be a good source: https://www.bitcoinmining.com/what-is-the-bitcoin-block-reward/

**Comment by alexdovzhanyn** [comment]
I was thinking something similar, but I'm not sure where a good starting point is

**Comment by alexdovzhanyn** [comment]
As per the latest code push, we are starting the block reward at 100 odyn, and then halving it every 200,000 blocks

**Comment by alexdovzhanyn** [comment]
All of this criteria is now met, according to the latest push
