### ISSUE TITLE
Running Development setup from README caused Exception

### ISSUE THREAD

**Issue by Pavel-Durov** [alexdovzhanyn/odyn#2]
I followed **Development setup** steps and I've encountered the following exception:

```
$ ruby node/node.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from node/node.rb:5:in `<main>'
```

> OS: OS X 

> ruby --version
> ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

> bundle --version
> Bundler version 1.16.1

> gem --version
> 2.5.2

Did I miss something here? Is there any specific Ruby version I need to be running?

**Comment by Pavel-Durov** [comment]
Same thing with 

> ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

**Comment by alexdovzhanyn** [comment]
Ah this is my bad! I forgot to add pry as a dependency in the Gemfile. Would you mind opening the Gemfile and adding `gem 'pry'` to it? And then run bundle install again.

**Comment by Pavel-Durov** [comment]
Yep, no problem
 👍

**Comment by alexdovzhanyn** [comment]
Let me know if that works, and if it does, feel free to make a PR for that
