### ISSUE TITLE
Check UTXO source as part of consensus

### ISSUE THREAD

**Issue by alexdovzhanyn** [alexdovzhanyn/odyn#28]
Update the consensus algorithm to find the transaction to which a utxo is referring to, and verify that the utxo amount and address are the same values that we have stored in our blockchain. A possible shortcut is to check our own utxo store and validate against that instead (we believe we are an honest node)

**Comment by Pavel-Durov** [comment]
@alexdovzhanyn this shortcut is an optimization that we can make, but then **odyn** won't be a decentralized network by definition. Of course, we can trust our node but from other nodes perspective, this node will be a "God-like" node that's hard to trust :(

**Comment by alexdovzhanyn** [comment]
@Pavel-Durov I think you might be misunderstanding. Ultimately, our node uses the utxo store it knows is true before broadcasting the transaction further. Other nodes can verify for themselves as well

**Comment by alexdovzhanyn** [comment]
This has been completed in the latest push
